### ISSUE TITLE
Doku-Files unlesbar

### ISSUE THREAD

**Issue by birdie60** [tomcx/tame3#2]
Leider sind die beiden Doku-Files nicht lesbar / corrupted. Bitte neu hochladen!
LG S.Vogel

**Comment by tomcx** [comment]
Sorry, kann ich nicht nachvollziehen. Die PDF ist sowohl online als auch offline lesbar, die ODT (LibreOffice) macht offline auch keine Probleme. Mit 2 Rechnern unter Windows und Linux getestet.
